types = {
    "commissions": {
        'id': 'integer',
        'business_model': 'char',
        'warehouse': 'integer',
        'invoice_doc_id': 'integer',
        'invoice_name': 'char',
        'invoice_date': 'date',
        'invoice_origin': 'char',
        'partner_name': 'char',
        'salesperson_id': 'integer',
        'internal_reference': 'char',
        'product_name': 'char',
        'quantity': 'float',
        'price_unit': 'monetary',
        'price_subtotal': 'float',
        'purchase_name': 'char',
        'vendor_name': 'char',
        'product_cost': 'monetary',
        'cost_subtotal': 'monetary',
        'subtotal_commission': 'monetary',
        'subtotal_commission_pct': 'float',
        'subtotal_contribution_pct': 'float',
        'customer_commission_pct': 'float',
        'customer_commission': 'monetary',
        'product_total_cost': 'monetary',
        'product_total_commission': 'monetary',
        'total_utility_pct': 'float',
        'total_contribution_pct': 'float',
        'create_date': 'date',
        'write_date': 'date',
    },
}